version: '3.3'
services:
    service:
        container_name: service
        build: 
            context: ./service  
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - PORT=5000
    scraper:
        container_name: scraper
        build:  
            context: ./scraper  
            dockerfile: Dockerfile
        ports:
            - 5001:5001
        environment:
            - PORT=5001
    dynamodb-local:
        image: amazon/dynamodb-local:latest
        container_name: dynamodb-local
        ports:
            - "8000:8000"